const theme = {
    form_caption_color: '#999',
    form_caption_margin: '0 0 0 185px',
    form_caption_max_width: '300px',
    form_caption_padding: '0 0 0 14px',
    form_container_background: 'transparent',
    form_container_border: 'none',
    form_container_padding: '0 20px',
    form_container_width: '650px',
    form_input_background: 'white',
    form_input_border_radius: '8px',
    form_input_border: '1px solid #a6a6a6',
    form_input_padding: '0.4em 0 0',
    form_input_text_color: 'black',
    form_input_text_size: '100%',
    form_input_width: '300px',
    form_label_text_align: 'right',
    form_label_text_color: 'black',
    form_label_text_size: '18px',
    form_label_width: '185px',
    form_line_wrapper_padding: '20px',
    form_required_mark_color: 'rgb(230, 42, 0)',
    form_required_mark_size: '18px',
    global_font_family: '"Helvetica Neue", Helvetica, Arial, sans-serif',
    header_background_position: 'center, 0',
    header_background: 'url(https://www.jackpotjoy.ppc2.pgt01.gamesysgames.com/assets/4.0.921/jackpotjoy/pages/mobile/skin/css/../img/header/header-sparkles.svg) #0054ba',
    header_border_bottom: 'none',
    header_border_shadow: '0 2px 3px rgba(0,0,0,.2)',
    header_venture_logo_size: '70%',
    header_venture_logo: 'url(https://www.jackpotjoy.ppc2.pgt01.gamesysgames.com/assets/4.0.921/multiplatform/pages/skin/css/../img/header/logo.png) no-repeat center',
    next_page_button_background: 'transparent',
    next_page_button_border: 'none',
    next_page_button_box_shadow: 'none',
    next_page_button_text_color: 'white',
    next_page_button_text_shadow: 'none',
    next_page_button_text_size: '19px',
    page_background: '#0639b6',
    page_title_background: 'transparent',
    page_title_text_color: 'rgb(204, 0, 0);',
    page_title_text_size: '21.6px'
}

export default theme;
