const theme = {
    form_caption_color: '#999',
    form_caption_margin: '0 0 0 185px',
    form_caption_max_width: '300px',
    form_caption_padding: '0 0 0 14px',
    form_container_background: 'white',
    form_container_border: '1px solid black',
    form_container_padding: '0 20px',
    form_container_width: '650px',
    form_input_background: 'white',
    form_input_border_radius: '4px',
    form_input_border: '1px solid #aaa',
    form_input_padding: '0.3em 8px',
    form_input_text_color: '#383838',
    form_input_text_size: '13pt',
    form_input_width: '300px',
    form_label_text_align: 'right',
    form_label_text_color: 'rgb(56, 56, 56)',
    form_label_text_size: '18px',
    form_label_width: '185px',
    form_line_wrapper_padding: '20px',
    form_required_mark_color: '#cc0000',
    form_required_mark_size: '18px',
    global_font_family: '"Helvetica Neue", Helvetica, Arial, sans-serif',
    header_background_position: '0',
    header_background: 'black',
    header_border_bottom: '1px solid white',
    header_border_shadow: '0 2px 3px rgba(0,0,0,.2)',
    header_venture_logo_size: '78%',
    header_venture_logo: 'url(https://www.starspins.ppc2.pgt01.gamesysgames.com/assets/4.0.921/starspins/pages/mobile/skin/css/../img/logo.png) no-repeat top right',
    next_page_button_background: 'linear-gradient(to bottom,rgb(255,179,39) 0%,rgb(255,207,57) 100%)',
    next_page_button_box_shadow: '0 2px 4px rgba(0,0,0,0.4), 0 1px 0 rgba(255,255,255,0.2) inset',
    next_page_button_text_color: 'white',
    next_page_button_text_shadow: '0px -1px black',
    next_page_button_text_size: '19px',
    page_background: 'white',
    page_title_background: 'black',
    page_title_text_color: '#f7d445',
    page_title_text_size: '18px'
}

export default theme;
